services:
    quakejs:
        container_name: quakejs
        build:
            context: .
            dockerfile: Dockerfile
        image: treyyoder/quakejs:latest
        restart: unless-stopped
        ports:
            - "8080:80"
